$(function () {
  let dealerPaymrntStatus = [
    {
      ShipToNumber: 102302,
      Checked: false,
      IsLocked: false,
      LockUser: "",
      EarningsActivityID: 0,
      PayParticipantLookupID: 430902,
      PaymentStatus: "No Earned Payment",
      HLC: "7184846",
      HLCAcctNum: "1169847",
      LegalName: "Legal Name 1",
      TotalUnits: 0.0,
      LoyaltyPercentage: 0.0,
      PercentToGoal: 0.0,
      CalculatedPayment: null,
      CurrentPayment: {
        DisplayCode: "USD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 322316.0,
        FormattedAmount: "$322,316.00",
        FormatString: "${0:n2}",
      },
      CurrentPaymentAmount: 322316.0,
      YTDEarned: {
        DisplayCode: "USD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 0.0,
        FormattedAmount: "$0.00",
        FormatString: "${0:n2}",
      },
      YTDPaid: {
        DisplayCode: "USD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 0.0,
        FormattedAmount: "$0.00",
        FormatString: "${0:n2}",
      },
      DealerStatus: "Active",
      DaysInStatus: 3,
      LastEditedBy: "Test 1",
      Approved: "2024-04-22T00:00:00",
      SentPaymentFor: "2024-04-29T00:00:00",
      Status: "View",
      StatusID: 0,
      PromotionID: 9227042,
      PeriodID: "1",
      PaymentCode: null,
      FormNumber: null,
      InvoiceNumber: null,
      InvoiceDate: null,
      ParticipantIsDirectDealer: false,
      IsMRTOliver: false,
      Payments: null,
      Comments: null,
      PromoName: "#VJ_AAD_136905_01",
    },
    {
      ShipToNumber: 122302,
      Checked: false,
      IsLocked: false,
      LockUser: "",
      EarningsActivityID: 0,
      PayParticipantLookupID: 430901,
      PaymentStatus: "Deferred",
      HLC: "7168706",
      HLCAcctNum: "1391310",
      LegalName: "Legal Name 2",
      TotalUnits: 0.0,
      LoyaltyPercentage: 0.0,
      PercentToGoal: 0.0,
      CalculatedPayment: null,
      CurrentPayment: {
        DisplayCode: "USD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 2342316.0,
        FormattedAmount: "$2,342,316.00",
        FormatString: "${0:n2}",
      },
      CurrentPaymentAmount: 2342316.0,
      YTDEarned: {
        DisplayCode: "USD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 0.0,
        FormattedAmount: "$0.00",
        FormatString: "${0:n2}",
      },
      YTDPaid: {
        DisplayCode: "USD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 0.0,
        FormattedAmount: "$0.00",
        FormatString: "${0:n2}",
      },
      DealerStatus: "Active",
      DaysInStatus: 3,
      LastEditedBy: "Test 1",
      Approved: "2024-04-22T00:00:00",
      SentPaymentFor: "2024-04-29T00:00:00",
      Status: "View",
      StatusID: 0,
      PromotionID: 9227042,
      PeriodID: "1",
      PaymentCode: null,
      FormNumber: null,
      InvoiceNumber: null,
      InvoiceDate: null,
      ParticipantIsDirectDealer: false,
      IsMRTOliver: false,
      Payments: null,
      Comments: null,
      PromoName: "#VJ_Offercode",
    },
    {
      ShipToNumber: 112302,
      Checked: false,
      IsLocked: false,
      LockUser: "",
      EarningsActivityID: 0,
      PayParticipantLookupID: 430903,
      PaymentStatus: "Approved",
      HLC: "9216825",
      HLCAcctNum: "1543373",
      LegalName: "Legal Name 3",
      TotalUnits: 0.0,
      LoyaltyPercentage: 0.0,
      PercentToGoal: 0.0,
      CalculatedPayment: null,
      CurrentPayment: {
        DisplayCode: "USD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 2316.0,
        FormattedAmount: "$2,316.00",
        FormatString: "${0:n2}",
      },
      CurrentPaymentAmount: 2316.0,
      YTDEarned: {
        DisplayCode: "USD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 0.0,
        FormattedAmount: "$0.00",
        FormatString: "${0:n2}",
      },
      YTDPaid: {
        DisplayCode: "USD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 0.0,
        FormattedAmount: "$0.00",
        FormatString: "${0:n2}",
      },
      DealerStatus: "Active",
      DaysInStatus: 10,
      LastEditedBy: "Test 1",
      Approved: "2024-04-22T00:00:00",
      SentPaymentFor: null,
      Status: "Edit",
      StatusID: 0,
      PromotionID: 9227042,
      PeriodID: "1",
      PaymentCode: null,
      FormNumber: null,
      InvoiceNumber: null,
      InvoiceDate: null,
      ParticipantIsDirectDealer: false,
      IsMRTOliver: false,
      Payments: null,
      Comments: null,
      PromoName: "VJ_GLCODE",
    },
    {
      ShipToNumber: 112202,
      Checked: false,
      IsLocked: false,
      LockUser: "",
      EarningsActivityID: 0,
      PayParticipantLookupID: 430899,
      PaymentStatus: "Deferred",
      HLC: "7184846",
      HLCAcctNum: "1169847",
      LegalName: "Legal Name 4",
      TotalUnits: 0.0,
      LoyaltyPercentage: 0.0,
      PercentToGoal: 0.0,
      CalculatedPayment: null,
      CurrentPayment: {
        DisplayCode: "USD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 322316.0,
        FormattedAmount: "$322,316.00",
        FormatString: "${0:n2}",
      },
      CurrentPaymentAmount: 322316.0,
      YTDEarned: {
        DisplayCode: "USD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 0.0,
        FormattedAmount: "$0.00",
        FormatString: "${0:n2}",
      },
      YTDPaid: {
        DisplayCode: "USD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 0.0,
        FormattedAmount: "$0.00",
        FormatString: "${0:n2}",
      },
      DealerStatus: "Active",
      DaysInStatus: 3,
      LastEditedBy: "Test 1",
      Approved: "2024-04-22T00:00:00",
      SentPaymentFor: "2024-04-29T00:00:00",
      Status: "View",
      StatusID: 0,
      PromotionID: 9227042,
      PeriodID: "1",
      PaymentCode: null,
      FormNumber: null,
      InvoiceNumber: null,
      InvoiceDate: null,
      ParticipantIsDirectDealer: false,
      IsMRTOliver: false,
      Payments: null,
      Comments: null,
      PromoName: "#VJ_AAD_136905_01",
    },
    {
      ShipToNumber: 234599,
      Checked: false,
      IsLocked: false,
      LockUser: "",
      EarningsActivityID: 0,
      PayParticipantLookupID: 430898,
      PaymentStatus: "Sent For Payment",
      HLC: "7168706",
      HLCAcctNum: "1391310",
      LegalName: "Legal Name 5",
      TotalUnits: 0.0,
      LoyaltyPercentage: 0.0,
      PercentToGoal: 0.0,
      CalculatedPayment: null,
      CurrentPayment: {
        DisplayCode: "USD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 2342316.0,
        FormattedAmount: "$2,342,316.00",
        FormatString: "${0:n2}",
      },
      CurrentPaymentAmount: 2342316.0,
      YTDEarned: {
        DisplayCode: "USD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 0.0,
        FormattedAmount: "$0.00",
        FormatString: "${0:n2}",
      },
      YTDPaid: {
        DisplayCode: "USD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 0.0,
        FormattedAmount: "$0.00",
        FormatString: "${0:n2}",
      },
      DealerStatus: "Active",
      DaysInStatus: 3,
      LastEditedBy: "Test 1",
      Approved: "2024-04-22T00:00:00",
      SentPaymentFor: "2024-04-29T00:00:00",
      Status: "View",
      StatusID: 0,
      PromotionID: 9227042,
      PeriodID: "1",
      PaymentCode: null,
      FormNumber: null,
      InvoiceNumber: null,
      InvoiceDate: null,
      ParticipantIsDirectDealer: false,
      IsMRTOliver: false,
      Payments: null,
      Comments: null,
      PromoName: "#VJ_Offercode",
    },
    {
      ShipToNumber: 345123,
      Checked: false,
      IsLocked: false,
      LockUser: "",
      EarningsActivityID: 0,
      PayParticipantLookupID: 430900,
      PaymentStatus: "Paid",
      HLC: "9216825",
      HLCAcctNum: "1543373",
      LegalName: "Legal Name 6",
      TotalUnits: 0.0,
      LoyaltyPercentage: 0.0,
      PercentToGoal: 0.0,
      CalculatedPayment: null,
      CurrentPayment: {
        DisplayCode: "USD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 2316.0,
        FormattedAmount: "$2,316.00",
        FormatString: "${0:n2}",
      },
      CurrentPaymentAmount: 2316.0,
      YTDEarned: {
        DisplayCode: "USD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 0.0,
        FormattedAmount: "$0.00",
        FormatString: "${0:n2}",
      },
      YTDPaid: {
        DisplayCode: "USD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 0.0,
        FormattedAmount: "$0.00",
        FormatString: "${0:n2}",
      },
      DealerStatus: "Active",
      DaysInStatus: 10,
      LastEditedBy: "Test 1",
      Approved: "2024-04-22T00:00:00",
      SentPaymentFor: null,
      Status: "Edit",
      StatusID: 0,
      PromotionID: 9227042,
      PeriodID: "1",
      PaymentCode: null,
      FormNumber: null,
      InvoiceNumber: null,
      InvoiceDate: null,
      ParticipantIsDirectDealer: false,
      IsMRTOliver: false,
      Payments: null,
      Comments: null,
      PromoName: "VJ_GLCODE",
    },
    {
      ShipToNumber: 321123,
      Checked: false,
      IsLocked: false,
      LockUser: "",
      EarningsActivityID: 0,
      PayParticipantLookupID: 429673,
      PaymentStatus: "Paid",
      HLC: "9210932",
      HLCAcctNum: "0362717",
      LegalName: "Legal Name 7",
      TotalUnits: 0.0,
      LoyaltyPercentage: 0.0,
      PercentToGoal: 0.0,
      CalculatedPayment: null,
      CurrentPayment: {
        DisplayCode: "CAD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 23.0,
        FormattedAmount: "23.00",
        FormatString: "{0:n2}",
      },
      CurrentPaymentAmount: 23.0,
      YTDEarned: {
        DisplayCode: "CAD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 0.0,
        FormattedAmount: "0.00",
        FormatString: "{0:n2}",
      },
      YTDPaid: {
        DisplayCode: "CAD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 0.0,
        FormattedAmount: "0.00",
        FormatString: "{0:n2}",
      },
      DealerStatus: "Active",
      DaysInStatus: 14,
      LastEditedBy: "Test 2",
      Approved: "2024-04-18T00:00:00",
      SentPaymentFor: null,
      Status: "Edit",
      StatusID: 0,
      PromotionID: 9227042,
      PeriodID: "1",
      PaymentCode: null,
      FormNumber: null,
      InvoiceNumber: null,
      InvoiceDate: null,
      ParticipantIsDirectDealer: false,
      IsMRTOliver: false,
      Payments: null,
      Comments: null,
      PromoName: "TestGl05",
    },
    {
      ShipToNumber: 234123,
      Checked: false,
      IsLocked: false,
      LockUser: "",
      EarningsActivityID: 0,
      PayParticipantLookupID: 429674,
      PaymentStatus: "Approved",
      HLC: "9211081",
      HLCAcctNum: "0362869",
      LegalName: "Legal Name 8",
      TotalUnits: 0.0,
      LoyaltyPercentage: 0.0,
      PercentToGoal: 0.0,
      CalculatedPayment: null,
      CurrentPayment: {
        DisplayCode: "CAD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 10.0,
        FormattedAmount: "10.00",
        FormatString: "{0:n2}",
      },
      CurrentPaymentAmount: 10.0,
      YTDEarned: {
        DisplayCode: "CAD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 0.0,
        FormattedAmount: "0.00",
        FormatString: "{0:n2}",
      },
      YTDPaid: {
        DisplayCode: "CAD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 0.0,
        FormattedAmount: "0.00",
        FormatString: "{0:n2}",
      },
      DealerStatus: "Active",
      DaysInStatus: 14,
      LastEditedBy: "Test 2",
      Approved: "2024-04-18T00:00:00",
      SentPaymentFor: null,
      Status: "Edit",
      StatusID: 0,
      PromotionID: 9227042,
      PeriodID: "1",
      PaymentCode: null,
      FormNumber: null,
      InvoiceNumber: null,
      InvoiceDate: null,
      ParticipantIsDirectDealer: false,
      IsMRTOliver: false,
      Payments: null,
      Comments: null,
      PromoName: "TestGl03",
    },
    {
      ShipToNumber: 321454,
      Checked: false,
      IsLocked: false,
      LockUser: "",
      EarningsActivityID: 0,
      PayParticipantLookupID: 429675,
      PaymentStatus: "Sent For Payment",
      HLC: "9211099",
      HLCAcctNum: "0362889",
      LegalName: "Legal Name 9",
      TotalUnits: 0.0,
      LoyaltyPercentage: 0.0,
      PercentToGoal: 0.0,
      CalculatedPayment: null,
      CurrentPayment: {
        DisplayCode: "CAD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 11.0,
        FormattedAmount: "11.00",
        FormatString: "{0:n2}",
      },
      CurrentPaymentAmount: 11.0,
      YTDEarned: {
        DisplayCode: "CAD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 0.0,
        FormattedAmount: "0.00",
        FormatString: "{0:n2}",
      },
      YTDPaid: {
        DisplayCode: "CAD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 0.0,
        FormattedAmount: "0.00",
        FormatString: "{0:n2}",
      },
      DealerStatus: "Active",
      DaysInStatus: 10,
      LastEditedBy: "Test 2",
      Approved: "2024-04-18T00:00:00",
      SentPaymentFor: "2024-04-22T00:00:00",
      Status: "View",
      StatusID: 0,
      PromotionID: 9227042,
      PeriodID: "1",
      PaymentCode: null,
      FormNumber: null,
      InvoiceNumber: null,
      InvoiceDate: null,
      ParticipantIsDirectDealer: false,
      IsMRTOliver: false,
      Payments: null,
      Comments: null,
      PromoName: "TestGl01",
    },
    {
      ShipToNumber: 345345,
      Checked: false,
      IsLocked: false,
      LockUser: "",
      EarningsActivityID: 0,
      PayParticipantLookupID: 429676,
      PaymentStatus: "Approved",
      HLC: "9211376",
      HLCAcctNum: "0363169",
      LegalName: "Legal Name 10",
      TotalUnits: 0.0,
      LoyaltyPercentage: 0.0,
      PercentToGoal: 0.0,
      CalculatedPayment: null,
      CurrentPayment: {
        DisplayCode: "CAD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 24.0,
        FormattedAmount: "24.00",
        FormatString: "{0:n2}",
      },
      CurrentPaymentAmount: 24.0,
      YTDEarned: {
        DisplayCode: "CAD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 0.0,
        FormattedAmount: "0.00",
        FormatString: "{0:n2}",
      },
      YTDPaid: {
        DisplayCode: "CAD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 0.0,
        FormattedAmount: "0.00",
        FormatString: "{0:n2}",
      },
      DealerStatus: "Active",
      DaysInStatus: 14,
      LastEditedBy: "Test 2",
      Approved: "2024-04-18T00:00:00",
      SentPaymentFor: null,
      Status: "Edit",
      StatusID: 0,
      PromotionID: 9227042,
      PeriodID: "1",
      PaymentCode: null,
      FormNumber: null,
      InvoiceNumber: null,
      InvoiceDate: null,
      ParticipantIsDirectDealer: false,
      IsMRTOliver: false,
      Payments: null,
      Comments: null,
      PromoName: "TestGl04",
    },
    {
      ShipToNumber: 765567,
      Checked: false,
      IsLocked: false,
      LockUser: "",
      EarningsActivityID: 0,
      PayParticipantLookupID: 429677,
      PaymentStatus: "Pending",
      HLC: "9211418",
      HLCAcctNum: "0363211",
      LegalName: "Legal Name 11",
      TotalUnits: 0.0,
      LoyaltyPercentage: 0.0,
      PercentToGoal: 0.0,
      CalculatedPayment: null,
      CurrentPayment: {
        DisplayCode: "CAD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 22.0,
        FormattedAmount: "22.00",
        FormatString: "{0:n2}",
      },
      CurrentPaymentAmount: 22.0,
      YTDEarned: {
        DisplayCode: "CAD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 0.0,
        FormattedAmount: "0.00",
        FormatString: "{0:n2}",
      },
      YTDPaid: {
        DisplayCode: "CAD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 0.0,
        FormattedAmount: "0.00",
        FormatString: "{0:n2}",
      },
      DealerStatus: "Active",
      DaysInStatus: 14,
      LastEditedBy: "Test 2",
      Approved: "2024-04-18T00:00:00",
      SentPaymentFor: null,
      Status: "Edit",
      StatusID: 0,
      PromotionID: 9227042,
      PeriodID: "1",
      PaymentCode: null,
      FormNumber: null,
      InvoiceNumber: null,
      InvoiceDate: null,
      ParticipantIsDirectDealer: false,
      IsMRTOliver: false,
      Payments: null,
      Comments: null,
      PromoName: "TestGl02",
    },
    {
      ShipToNumber: 102302,
      Checked: false,
      IsLocked: false,
      LockUser: "",
      EarningsActivityID: 0,
      PayParticipantLookupID: 429672,
      PaymentStatus: "Pending",
      HLC: "7585614",
      HLCAcctNum: "0350916",
      LegalName: "Legal Name 12",
      TotalUnits: 0.0,
      LoyaltyPercentage: 0.0,
      PercentToGoal: 0.0,
      CalculatedPayment: null,
      CurrentPayment: {
        DisplayCode: "CAD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 22.0,
        FormattedAmount: "22.00",
        FormatString: "{0:n2}",
      },
      CurrentPaymentAmount: 22.0,
      YTDEarned: {
        DisplayCode: "CAD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 0.0,
        FormattedAmount: "0.00",
        FormatString: "{0:n2}",
      },
      YTDPaid: {
        DisplayCode: "CAD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 0.0,
        FormattedAmount: "0.00",
        FormatString: "{0:n2}",
      },
      DealerStatus: "Disabled",
      DaysInStatus: 14,
      LastEditedBy: "Test 2",
      Approved: "2024-04-18T00:00:00",
      SentPaymentFor: null,
      Status: "Edit",
      StatusID: 0,
      PromotionID: 9227042,
      PeriodID: "1",
      PaymentCode: null,
      FormNumber: null,
      InvoiceNumber: null,
      InvoiceDate: null,
      ParticipantIsDirectDealer: false,
      IsMRTOliver: false,
      Payments: null,
      Comments: null,
      PromoName: "TestGl02",
    },
    {
      ShipToNumber: 123213,
      Checked: false,
      IsLocked: false,
      LockUser: "",
      EarningsActivityID: 0,
      PayParticipantLookupID: 429671,
      PaymentStatus: "Sent For Payment",
      HLC: "7537413",
      HLCAcctNum: "0702231",
      LegalName: "Legal Name 13",
      TotalUnits: 0.0,
      LoyaltyPercentage: 0.0,
      PercentToGoal: 0.0,
      CalculatedPayment: null,
      CurrentPayment: {
        DisplayCode: "CAD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 11.0,
        FormattedAmount: "11.00",
        FormatString: "{0:n2}",
      },
      CurrentPaymentAmount: 11.0,
      YTDEarned: {
        DisplayCode: "CAD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 0.0,
        FormattedAmount: "0.00",
        FormatString: "{0:n2}",
      },
      YTDPaid: {
        DisplayCode: "CAD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 0.0,
        FormattedAmount: "0.00",
        FormatString: "{0:n2}",
      },
      DealerStatus: "Active",
      DaysInStatus: 10,
      LastEditedBy: "Test 2",
      Approved: "2024-04-18T00:00:00",
      SentPaymentFor: "2024-04-22T00:00:00",
      Status: "View",
      StatusID: 0,
      PromotionID: 9227042,
      PeriodID: "1",
      PaymentCode: null,
      FormNumber: null,
      InvoiceNumber: null,
      InvoiceDate: null,
      ParticipantIsDirectDealer: false,
      IsMRTOliver: false,
      Payments: null,
      Comments: null,
      PromoName: "TestGl01",
    },
    {
      ShipToNumber: 123123,
      Checked: false,
      IsLocked: false,
      LockUser: "",
      EarningsActivityID: 0,
      PayParticipantLookupID: 429463,
      PaymentStatus: "No Earned Payment",
      HLC: "7184846",
      HLCAcctNum: "1169847",
      LegalName: "Legal Name 14",
      TotalUnits: 0.0,
      LoyaltyPercentage: 0.0,
      PercentToGoal: 0.0,
      CalculatedPayment: null,
      CurrentPayment: {
        DisplayCode: "USD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 322316.0,
        FormattedAmount: "$322,316.00",
        FormatString: "${0:n2}",
      },
      CurrentPaymentAmount: 322316.0,
      YTDEarned: {
        DisplayCode: "USD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 0.0,
        FormattedAmount: "$0.00",
        FormatString: "${0:n2}",
      },
      YTDPaid: {
        DisplayCode: "USD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 0.0,
        FormattedAmount: "$0.00",
        FormatString: "${0:n2}",
      },
      DealerStatus: "Active",
      DaysInStatus: 105,
      LastEditedBy: "Test 1",
      Approved: null,
      SentPaymentFor: null,
      Status: "View",
      StatusID: 0,
      PromotionID: 9227042,
      PeriodID: "1",
      PaymentCode: null,
      FormNumber: null,
      InvoiceNumber: null,
      InvoiceDate: null,
      ParticipantIsDirectDealer: false,
      IsMRTOliver: false,
      Payments: null,
      Comments: null,
      PromoName: "DJ_TEST",
    },
    {
      ShipToNumber: 324242,
      Checked: false,
      IsLocked: false,
      LockUser: "",
      EarningsActivityID: 0,
      PayParticipantLookupID: 429462,
      PaymentStatus: "No Earned Payment",
      HLC: "7168706",
      HLCAcctNum: "1391310",
      LegalName: "Legal Name 15",
      TotalUnits: 0.0,
      LoyaltyPercentage: 0.0,
      PercentToGoal: 0.0,
      CalculatedPayment: null,
      CurrentPayment: {
        DisplayCode: "USD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 2342316.0,
        FormattedAmount: "$2,342,316.00",
        FormatString: "${0:n2}",
      },
      CurrentPaymentAmount: 2342316.0,
      YTDEarned: {
        DisplayCode: "USD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 0.0,
        FormattedAmount: "$0.00",
        FormatString: "${0:n2}",
      },
      YTDPaid: {
        DisplayCode: "USD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 0.0,
        FormattedAmount: "$0.00",
        FormatString: "${0:n2}",
      },
      DealerStatus: "Active",
      DaysInStatus: 3,
      LastEditedBy: "Test 1",
      Approved: "2024-01-24T00:00:00",
      SentPaymentFor: "2024-04-29T00:00:00",
      Status: "View",
      StatusID: 0,
      PromotionID: 9227042,
      PeriodID: "1",
      PaymentCode: null,
      FormNumber: null,
      InvoiceNumber: null,
      InvoiceDate: null,
      ParticipantIsDirectDealer: false,
      IsMRTOliver: false,
      Payments: null,
      Comments: null,
      PromoName: "``Double``_`Single`_`Tick`",
    },
    {
      ShipToNumber: 112233,
      Checked: false,
      IsLocked: false,
      LockUser: "",
      EarningsActivityID: 0,
      PayParticipantLookupID: 429464,
      PaymentStatus: "Approved",
      HLC: "9216825",
      HLCAcctNum: "1543373",
      LegalName: "Legal Name 16",
      TotalUnits: 0.0,
      LoyaltyPercentage: 0.0,
      PercentToGoal: 0.0,
      CalculatedPayment: null,
      CurrentPayment: {
        DisplayCode: "USD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 2316.0,
        FormattedAmount: "$2,316.00",
        FormatString: "${0:n2}",
      },
      CurrentPaymentAmount: 2316.0,
      YTDEarned: {
        DisplayCode: "USD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 0.0,
        FormattedAmount: "$0.00",
        FormatString: "${0:n2}",
      },
      YTDPaid: {
        DisplayCode: "USD",
        Symbol: "$",
        NumberFormat: "{0:n2}",
        Amount: 0.0,
        FormattedAmount: "$0.00",
        FormatString: "${0:n2}",
      },
      DealerStatus: "Active",
      DaysInStatus: 105,
      LastEditedBy: "Test 1",
      Approved: "2024-01-18T00:00:00",
      SentPaymentFor: null,
      Status: "Edit",
      StatusID: 0,
      PromotionID: 9227042,
      PeriodID: "1",
      PaymentCode: null,
      FormNumber: null,
      InvoiceNumber: null,
      InvoiceDate: null,
      ParticipantIsDirectDealer: false,
      IsMRTOliver: false,
      Payments: null,
      Comments: null,
      PromoName: "Test",
    },
  ];

  const statusCount = dealerPaymrntStatus.reduce(function (prev, cur) {
    prev[cur.PaymentStatus] = (prev[cur.PaymentStatus] || 0) + 1;
    return prev;
  }, {});

  const {
    Approved: approved,
    Deferred: deferred,
    Paid: paid,
    Pending: pending,
  } = statusCount;

  $(".approved").text(approved);
  $(".deferred").text(deferred);
  $(".paid").text(paid);
  $(".pending").text(pending);
  $(".nep").text(statusCount["No Earned Payment"]);
  $(".sfp").text(statusCount["Sent For Payment"]);

  const appendData = (rowData, filerType) => {
    if (filerType === "cardFilter" || filerType === "gridFilterData") {
      $("#dealerTable tbody").text("");
    }
    $.each(rowData, function (i, data) {
      var tblRow =
        "<tr>" +
        "<td>" +
        data.PromoName +
        "</td>" +
        "<td>" +
        data.ShipToNumber +
        "</td>" +
        "<td>" +
        data.PaymentStatus +
        "</td>" +
        "<td>" +
        data.LegalName +
        "</td>" +
        "<td>" +
        data.CurrentPaymentAmount +
        "</td>" +
        "<td>" +
        data.CurrentPaymentAmount +
        "</td>" +
        "<td>" +
        data.YTDEarned.FormattedAmount +
        "</td>" +
        "<td>" +
        data.YTDPaid.FormattedAmount +
        "</td>" +
        "<td>" +
        data.DealerStatus +
        "</td>" +
        "<td>" +
        data.DaysInStatus +
        "</td>" +
        "<td>" +
        data.LastEditedBy +
        "</td>" +
        "<td>" +
        data.Approved +
        "</td>" +
        "<td>" +
        data.SentPaymentFor +
        "</td>" +
        "</tr>";

      $(tblRow).appendTo("#dealerTable tbody");
    });
  };

  const getFilterType = (clickedFilter) => {
    let filterType = "";

    if (clickedFilter === "approved") {
      filterType = "Approved";
    } else if (clickedFilter === "paid") {
      filterType = "Paid";
    } else if (clickedFilter === "pending") {
      filterType = "Pending";
    } else if (clickedFilter === "sfp") {
      filterType = "Sent For Payment";
    } else if (clickedFilter === "nep") {
      filterType = "No Earned Payment";
    } else {
      filterType = "Deferred";
    }
    return filterType;
  };

  $(".cardFilter").click(function (e) {
    e.preventDefault();
    const clickedFilter = $(this).attr("id");
    const selectedCardFilter = getFilterType(clickedFilter);

    const result = dealerPaymrntStatus.filter(
      (data) => data.PaymentStatus === selectedCardFilter
    );

    appendData(result, "cardFilter");
  });
  const getGridData = (selectedCbValue) => {
    const selectedFilterValue = [];
    const getFilterDara = selectedCbValue.map((value) => {
      const filterdVal = getFilterType(value);
      selectedFilterValue.push(filterdVal);
      return null;
    });

    const gridResult = dealerPaymrntStatus.filter(
      (data) =>
        data.PaymentStatus === selectedFilterValue[0] ||
        data.PaymentStatus === selectedFilterValue[1] ||
        data.PaymentStatus === selectedFilterValue[2] ||
        data.PaymentStatus === selectedFilterValue[3] ||
        data.PaymentStatus === selectedFilterValue[4] ||
        data.PaymentStatus === selectedFilterValue[5] ||
        data.PaymentStatus === selectedFilterValue[6]
    );
    appendData(gridResult, "gridFilterData");
  };

  $("#example-allSelectedText-includeSelectAllOption").multiselect({
    includeSelectAllOption: true,
    allSelectedText: "No option left ...",
    onDropdownHide: function () {
      var selectedCbValue = $(
        "#example-allSelectedText-includeSelectAllOption"
      ).val();

      getGridData(selectedCbValue);
    },
  });

  appendData(dealerPaymrntStatus, "allData");
});
